import express from 'express';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
// Render assigns a dynamic PORT via environment variable (usually 10000 or custom)
const PORT = process.env.PORT || 3000;

// Health check endpoint for Render zero-downtime deploys and health checks
app.get('/healthz', (_req, res) => {
  res.status(200).send('OK');
});

// Serve static assets generated by Vite
const distPath = path.join(__dirname, 'dist');
app.use(express.static(distPath));

// Fallback to index.html for all client-side routes (SPA React Router)
app.get('*', (_req, res) => {
  res.sendFile(path.join(distPath, 'index.html'));
});

app.listen(PORT, '0.0.0.0', () => {
  console.log(`🚀 Production server is running on http://0.0.0.0:${PORT}`);
});
